# Generated by Django 4.2 on 2024-11-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10, unique=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='dashboard.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stock_symbol'], name='idx_stocks_symbol'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user'], name='idx_watchlist_userid'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['stock'], name='idx_watchlist_stockid'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'stock')},
        ),
    ]
