# Generated by Django 4.2 on 2025-01-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('name', 'price', 'billing_interval')},
        ),
    ]
