# Generated by Django 5.1.1 on 2024-09-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alert_profile_stock_trade_transaction_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
