# Generated by Django 4.2 on 2025-03-13 21:03

import django.core.validators
from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subscriptionplan_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), utils.utils.validate_image_file]),
        ),
    ]
