# Generated by Django 4.2 on 2024-11-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_address_remove_profile_total_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
