version: '3.8'  # Explicitly declaring version for better compatibility

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: gunicorn "tradeproject.asgi:application" -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --worker-tmp-dir /dev/shm --max-requests 1000 --max-requests-jitter 50 --timeout 120
    volumes:
      - static_files:/app/static
      - media_files:/app/media
    restart: always
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A tradeproject.celery_conf worker -l INFO
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A tradeproject.celery_conf beat -l INFO
    restart: always

volumes:
  static_files:  # Named volume for static files
  media_files:   # Named volume for media files
