services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: gunicorn "tradeproject.asgi:application" -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --worker-tmp-dir /dev/shm --max-requests 1000 --max-requests-jitter 50 --timeout 120
    volumes:
      - static_files:/app/static
      - media_files:/app/media
    restart: always
    networks:
      - dokploy-network
    ports:
      - 8000

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A tradeproject.celery_conf worker -l INFO
    restart: always
    networks:
      - dokploy-network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A tradeproject.celery_conf beat -l INFO
    restart: always
    networks:
      - dokploy-network

volumes:
  static_files:
  media_files:

networks:
  dokploy-network:
    external: true