# Generated by Django 4.2 on 2025-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(max_length=10),
        ),
    ]
